"""
entry_exit.py
=============
Per-camera entry / exit accounting on top of stable global IDs (SIDs).

Rules (from spec):
  * A global ID seen for the first time on this camera -> total_entries += 1
  * A global ID that has been seen but is absent for exit_timeout_sec -> exit
  * Re-entry of the same ID after a previous exit counts as a fresh entry
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field


@dataclass
class _TrackInfo:
    entry_time: float
    last_seen: float
    confidence: float = 0.0
    bbox: tuple[float, float, float, float] | None = None


@dataclass
class ExitEvent:
    sid: str
    exit_time: float


class EntryExitTracker:
    """Stateful tracker of which global IDs are currently 'inside' the camera view.

    Not thread-safe; the runner owns one per camera and only touches it
    from that camera's worker thread.
    """

    def __init__(
        self,
        exit_timeout_sec: float = 2.0,
        shared_dwell: dict[str, float] | None = None,
        shared_dwell_lock=None,
        peer_active=None,
    ) -> None:
        self.exit_timeout_sec = float(exit_timeout_sec)
        self.total_entries: int = 0
        self.total_exits: int = 0
        self._active: dict[str, _TrackInfo] = {}
        # Accumulated dwell across all *completed* visits per SID. When a
        # cross-camera dict is passed in (org-shared), all cameras of an org
        # write to the same dict so dwell is global-per-SID. Falls back to a
        # local dict if no shared one is supplied (per-camera semantics).
        self._lifetime_dwell_sec: dict[str, float] = (
            shared_dwell if shared_dwell is not None else {}
        )
        self._dwell_lock = shared_dwell_lock
        # Per-camera-only accumulator: completed dwell on *this* camera for
        # every SID that has visited it. Never shared org-wide, so it gives
        # a true "avg across everyone who has visited this cam" number.
        self._cam_lifetime_dwell_sec: dict[str, float] = {}
        # Optional callable returning a list of (cam_id, _TrackInfo)-like
        # entries for this SID currently active on *other* cameras of the
        # same org. Used to add their in-progress visit time so the dwell
        # number is truly global.
        self._peer_active = peer_active
        # ring buffer of the last N exits (used by DwellTracker fallback).
        self._recent_exits: list[tuple[str, float, float]] = []   # (sid, dwell, exit_time)
        self._recent_exit_cap: int = 32

    # ── observe / sweep ──────────────────────────────────────────────────────

    def observe(
        self,
        sid: str,
        bbox: tuple[float, float, float, float] | None,
        confidence: float,
        now: float | None = None,
    ) -> bool:
        """Mark `sid` as visible this frame. Returns True if this was a *new*
        entry (i.e., the ID was not previously inside the view)."""
        now = time.time() if now is None else now
        info = self._active.get(sid)
        if info is None:
            self._active[sid] = _TrackInfo(
                entry_time=now,
                last_seen=now,
                confidence=float(confidence),
                bbox=bbox,
            )
            self.total_entries += 1
            return True
        info.last_seen = now
        info.confidence = float(confidence)
        info.bbox = bbox
        return False

    def sweep(self, now: float | None = None) -> list[ExitEvent]:
        """Drop active IDs whose last_seen is older than the timeout. Returns
        the exit events generated by this sweep (empty if none)."""
        now = time.time() if now is None else now
        cutoff = now - self.exit_timeout_sec
        events: list[ExitEvent] = []
        for sid in list(self._active.keys()):
            info = self._active[sid]
            if info.last_seen < cutoff:
                dwell = max(0.0, info.last_seen - info.entry_time)
                if self._dwell_lock is not None:
                    with self._dwell_lock:
                        self._lifetime_dwell_sec[sid] = (
                            self._lifetime_dwell_sec.get(sid, 0.0) + dwell
                        )
                else:
                    self._lifetime_dwell_sec[sid] = (
                        self._lifetime_dwell_sec.get(sid, 0.0) + dwell
                    )
                self._cam_lifetime_dwell_sec[sid] = (
                    self._cam_lifetime_dwell_sec.get(sid, 0.0) + dwell
                )
                events.append(ExitEvent(sid=sid, exit_time=info.last_seen))
                self.total_exits += 1
                self._recent_exits.append((sid, dwell, info.last_seen))
                if len(self._recent_exits) > self._recent_exit_cap:
                    del self._recent_exits[: len(self._recent_exits) - self._recent_exit_cap]
                self._active.pop(sid, None)
        return events

    # ── accessors ────────────────────────────────────────────────────────────

    @property
    def current_occupancy(self) -> int:
        return len(self._active)

    @property
    def net_count(self) -> int:
        return self.total_entries - self.total_exits

    def active_items(self) -> list[tuple[str, _TrackInfo]]:
        return list(self._active.items())

    def recent_exits(self, n: int = 10) -> list[tuple[str, float, float]]:
        return self._recent_exits[-n:]

    def cam_visitor_dwell_sec(self, now: float | None = None) -> list[float]:
        """Per-SID total dwell on *this camera*, one value per unique SID that
        has visited this camera (completed visits + any in-progress visit).
        Used to compute the camera-local average across every visitor."""
        now = time.time() if now is None else now
        totals = dict(self._cam_lifetime_dwell_sec)
        for sid, info in self._active.items():
            totals[sid] = totals.get(sid, 0.0) + max(0.0, now - info.entry_time)
        return list(totals.values())

    def lifetime_dwell_sec(self, sid: str, now: float | None = None) -> float:
        """Total dwell accumulated for `sid` across all visits, including any
        in-progress visit. When a shared dwell dict and ``peer_active`` hook
        are wired (org-shared mode), this returns the global cross-camera
        total: completed visits anywhere + in-progress visits on every
        camera that currently sees the SID."""
        if self._dwell_lock is not None:
            with self._dwell_lock:
                total = self._lifetime_dwell_sec.get(sid, 0.0)
        else:
            total = self._lifetime_dwell_sec.get(sid, 0.0)
        now = time.time() if now is None else now

        info = self._active.get(sid)
        if info is not None:
            total += max(0.0, now - info.entry_time)

        if self._peer_active is not None:
            for entry_time in self._peer_active(sid):
                total += max(0.0, now - float(entry_time))

        return total
